create table Players
(
    id int generated by default as identity primary key ,
    name varchar(100) unique not null
);

create table Matches
(
    id int generated by default as identity primary key ,
    player1_id int references Players(id) not null,
    player2_id int references Players(id) not null,
    winner_id int references Players(id) not null,

check (player1_id <> player2_id) ,
check (winner_id = player1_id or winner_id = player2_id or winner_id IS NULL)
);